CREATE TABLE CUSTOMER
(
    ID BIGINT PRIMARY KEY,
    FIRST_NAME  VARCHAR(16) NOT NULL,
    LAST_NAME   VARCHAR(16) NOT NULL
);

CREATE TABLE PHONE
(
    ID       BIGINT PRIMARY KEY,
    PHONE_NO VARCHAR(16) NOT NULL,
    ACTIVE   CHAR(1)     NOT NULL
);

CREATE TABLE CUSTOMER_PHONE
(
    ID          BIGINT PRIMARY KEY,
    CUSTOMER_ID BIGINT NOT NULL,
    PHONE_ID    BIGINT NOT NULL
);

ALTER TABLE CUSTOMER_PHONE ADD CONSTRAINT FK_CUSTOMER_PHONE_CUSTOMER FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(ID)  ON DELETE CASCADE;
ALTER TABLE CUSTOMER_PHONE ADD CONSTRAINT FK_CUSTOMER_PHONE_PHONE FOREIGN KEY (PHONE_ID) REFERENCES PHONE(ID)  ON DELETE CASCADE;